# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=25, null=True)),
                ('q11', models.CharField(max_length=5, null=True)),
                ('q12', models.CharField(max_length=5, null=True)),
                ('q13', models.CharField(max_length=5, null=True)),
                ('q14', models.CharField(max_length=5, null=True)),
                ('q1_tot', models.CharField(max_length=5, null=True)),
                ('q21', models.CharField(max_length=5, null=True)),
                ('q22', models.CharField(max_length=5, null=True)),
                ('q23', models.CharField(max_length=5, null=True)),
                ('q24', models.CharField(max_length=5, null=True)),
                ('q25', models.CharField(max_length=5, null=True)),
                ('q2_tot', models.CharField(max_length=5, null=True)),
                ('q31', models.CharField(max_length=5, null=True)),
                ('q32', models.CharField(max_length=5, null=True)),
                ('q33', models.CharField(max_length=5, null=True)),
                ('q34', models.CharField(max_length=5, null=True)),
                ('q35', models.CharField(max_length=5, null=True)),
                ('q3_tot', models.CharField(max_length=5, null=True)),
                ('tot', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=25, null=True)),
                ('q11', models.CharField(max_length=10000, null=True)),
                ('q12', models.CharField(max_length=10000, null=True)),
                ('q13', models.CharField(max_length=10000, null=True)),
                ('q14', models.CharField(max_length=10000, null=True)),
                ('q21', models.CharField(max_length=10000, null=True)),
                ('q22', models.CharField(max_length=10000, null=True)),
                ('q23', models.CharField(max_length=10000, null=True)),
                ('q24', models.CharField(max_length=10000, null=True)),
                ('q25', models.CharField(max_length=10000, null=True)),
                ('q31', models.CharField(max_length=10000, null=True)),
                ('q32', models.CharField(max_length=10000, null=True)),
                ('q33', models.CharField(max_length=10000, null=True)),
                ('q34', models.CharField(max_length=10000, null=True)),
                ('q35', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
