# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=25)),
                ('question', models.CharField(max_length=1000)),
                ('prev_ppr', models.CharField(blank=True, max_length=25, null=True)),
                ('options', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(max_length=5000)),
                ('c_ky', models.CharField(blank=True, max_length=500, null=True)),
                ('v_ky', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_name', models.CharField(default='132038', max_length=25, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('q11', models.CharField(max_length=25)),
                ('q12', models.CharField(max_length=25)),
                ('q13', models.CharField(max_length=25)),
                ('q14', models.CharField(max_length=25)),
                ('q21', models.CharField(max_length=25)),
                ('q22', models.CharField(max_length=25)),
                ('q23', models.CharField(max_length=25)),
                ('q24', models.CharField(max_length=25)),
                ('q25', models.CharField(max_length=25)),
                ('q31', models.CharField(max_length=25)),
                ('q32', models.CharField(max_length=25)),
                ('q33', models.CharField(max_length=25)),
                ('q34', models.CharField(max_length=25)),
                ('q35', models.CharField(max_length=25)),
            ],
        ),
    ]
