# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='moderator_name',
            field=models.CharField(default='jd_gourea', max_length=25, null=True),
        ),
    ]
